force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/High_Value_Claim__c.field-meta.xml
<CustomField>
    <fullName>High_Value_Claim__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Value Claim</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Settlement_Date__c.field-meta.xml
<CustomField xsi:schemaLocation="http://soap.sforce.com/2006/04/metadata http://soap.sforce.com/2006/04/metadata.xsd">
    <fullName>Settlement_Date__c</fullName>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClaimHelper.cls
public with sharing class ClaimHelper extends TriggerHandler{
    //instantiate private variable references to trigger records
    private List<Claim__c> newRecords;
    private Map<Id, Claim__c> oldRecordsMap;

    public ClaimHelper(){
        //introduce private variabes to the constructor
        this.newRecords = (List<Claim__c>) Trigger.new;
        this.oldRecordsMap = (Trigger.oldMap != null) ? (Map<Id,Claim__c>) Trigger.oldMap : null;
    }
    
    public override void beforeInsert() {
        this.executeBeforeLogic();
        
    }
    public override void beforeUpdate() {
        this.executeBeforeLogic();
    }    

    private void executeBeforeLogic(){
        for (Claim__c claim : newRecords){
            //Calculate Claim Duration: Days_Open__c 
            if(claim.Incident_Date__c != null && 
                claim.Status__c != 'Settled' && 
                claim.Settlement_Date__c == null){
                claim.Days_Open__c = claim.Incident_Date__c.daysBetween(Date.today());
            }else  
            if (claim.Status__c == 'Settled' &&
                claim.Settlement_Date__c != null){
                claim.Days_Open__c = claim.Incident_Date__c.daysBetween(claim.Settlement_Date__c);
            } 
            //SCRUM-7: Intake Validation
            if (claim.Incident_Date__c != null &&
                claim.Settlement_Date__c != null && 
                claim.Incident_Date__c > claim.Settlement_Date__c){
                claim.Settlement_Date__c.addError('Settlement Date cannot be before the Incident Date.');
            }

            //SCRUM-7: Intake Validation moved into framework
            if(claim.Incident_Date__c != null && claim.Incident_Date__c > Date.today()){
                claim.Incident_Date__c.addError('Incident Date cannot be in the future.');
            }
            //SCRUM-12: Settlement Compliance
            If(claim.Status__c == 'Settled'){
                if (claim.Settlement_Amount__c == null || claim.Settlement_Amount__c <= 0){
                claim.Settlement_Amount__c.addError('A claim cannot be marked Settled with a $0 or blank payout.');
                }
            }
            else if(claim.Status__c == 'Denied'){
                claim.Settlement_Amount__c = 0;
            }
            //High value automation rule
            if(claim.Settlement_Amount__c > 15000 && claim.Status__c != 'Denied'){
                claim.High_Value_Claim__c = true;
            } else {
                claim.High_Value_Claim__c = false;
            }
        }        
    }
}